.build-template-mr:
    stage: build
    only:
        refs:
            - merge_requests
    image:  gitlab.goreact.com:4567/goreact/docker-containers/gr-tests-php:latest
    tags:
        - docker

.build-client-chrome-template:
    stage: build
    only:
        refs:
            - merge_requests
    image: gitlab.goreact.com:4567/goreact/docker-containers/gr-tests-chrome:latest
    tags:
        - docker

build-web-mr:
    extends: .build-template-mr
    only:
        changes:
            - web/**/*
            - gitlab-ci/build.yml
            - docker/web/**/*
            - docker/db/**/*
    cache:
        key: comforter-vendor
        paths:
            - web/vendor
            - web/node_modules
    script:
        - cd web/
        - cp .env.example .env
        - /usr/bin/php7 /usr/local/bin/composer install
    artifacts:
        paths:
            - web/.env
            - web/vendor/

build-client-mr:
    extends: .build-client-chrome-template
    only:
        changes:
            - client/**/*
            - gitlab-ci/build.yml
    script:
        - cd client/
        - yarn install
    artifacts:
        paths:
            - client
